global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "nginx_exporter"
    scrape_interval: 15s
    static_configs:
      - targets: ["nginx_exporter:9113"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "postgres_exporter"
    scrape_interval: 25s
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:9188"]